name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Ubuntu 20.04
            os: ubuntu-20.04
            install_dir: ~/libKeyFinder
            cmake_extras: -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - name: macOS 10.15
            os: macos-10.15
            install_dir: ~/libKeyFinder
            cmake_extras: -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - name: Windows 2019
            os: windows-2019
            install_dir: C:\libKeyFinder
            cmake_extras: >-
              -DVCPKG_TARGET_TRIPLET=x64-windows-static
              -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
              -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON
            cmake_config: --config RelWithDebInfo
            ctest_config: --build-config RelWithDebInfo

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: "[Ubuntu] Install FFTW"
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends fftw3-dev
    - name: "[macOS] Install FFTW"
      if: startsWith(matrix.os, 'macos')
      run: brew install fftw
    - name: "[Windows] Install FFTW"
      if: startsWith(matrix.os, 'windows')
      run: vcpkg install fftw3:x64-windows-static
    - name: Build
      run: |
        cmake ${{ matrix.cmake_extras }} -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${{ matrix.install_dir }} -S . -B build
        cmake ${{ matrix.cmake_config }} --build build --parallel 2
        cmake ${{ matrix.cmake_config }} --install build
    - name: Run Tests
      if: runner.os != 'Windows'
      run: ctest ${{ matrix.ctest_config }} --verbose
      working-directory: build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }} libKeyFinder build
        path: ${{ matrix.install_dir }}
